import { IsNotEmpty, IsMongoId, IsEnum, IsNumber, IsOptional,IsString, IsDate } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class CreatePaymentDto {
  @IsNotEmpty()
  @IsMongoId()
  @ApiProperty({ description: "Customer's UserID", example: '' })
  customer: string;

  @IsNotEmpty()
  @IsMongoId()
  @ApiProperty({ description: "OrderID", example: '' })
  order: string;

  @IsNotEmpty()
  @IsEnum(['cash', 'esewa','khalti','fonepay'])
  @ApiProperty({ description: "Payment Method", example: 'cash, esewa, khalti, fonepay' })
  paymentMethod: string;

  @IsNotEmpty()
  @IsNumber()
  @ApiProperty({description:'Total Amount in NPR',example:''})
  amount: number;

  @IsOptional()
  @IsEnum(['pending', 'paid', 'failed','refund', 'cancelled'])
  @ApiPropertyOptional({description:'Payment status',example:'pending, paid, failed, refund, cancelled'})
  paymentStatus?: string|null;

  @IsOptional()
  @ApiPropertyOptional({description:'Payment token generated by system for cash pay ',example:''})
  token?: string | null;

  @IsOptional()
  @IsDate()
  @ApiPropertyOptional({ description: 'Payment date', example: '' })
  paymentDate?: Date;

}
