security:
  allowedOrigins:
    - http://localhost:3000
    - http://localhost:8080
    - https://canteen.icimod.org
  disallowedRoutes:
    - ^/logout$/
    - ^/error
    - ^/delete-user
baseURL:
  - https://canteen.icimod.org/api
ignoreControllers:
  - ControllerScannerController
  - AuthController
  - AppController
  - AnalyticsController
  - DiscountController
  - OrderTimeFrameController
     
     
     